/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _SncBtl_MainGuitar_h_
#define _SncBtl_MainGuitar_h_
//---------------------------------------------------------------------------------
extern const unsigned char SncBtl_MainGuitar[];
extern const int SncBtl_MainGuitar_size;
//---------------------------------------------------------------------------------
#endif //_SncBtl_MainGuitar_h_
//---------------------------------------------------------------------------------
